// Generated by unRap v1.06 by Kegetys

class CfgMusic {
	class A3LTheme {
		name = "A3L Theme";
		sound[] = {"\A3L_client2\music\thisiswar.ogg", 1, 1};
		duration = 183;
		theme = "safe";
		musicClass = "Lead";
	};
};
