// Generated by unRap v1.06 by Kegetys

class CfgSounds {
	class bankAlarm {
		name = "bankAlarm";
		sound[] = {"\A3L_Client2\sounds\bankAlarm.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class carAlarm {
		name = "carAlarm";
		sound[] = {"\A3L_Client2\sounds\carAlarm.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class c4_buttons {
		name = "C4 button sound";
		sound[] = {"\A3L_Client2\bloop.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class lockpicksound {
		name = "lockpicksound";
		sound[] = {"\A3L_Client2\sounds\lockpick.ogg", 1, 1, 30};
		titles[] = {0, ""};
	};
	
	class CarLocked {
		name = "Car Locked";
		sound[] = {"\A3L_Client2\sounds\car_lock.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class CarUnlocked {
		name = "Car Unlocked";
		sound[] = {"\A3L_Client2\sounds\unlock.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class PatDown {
		name = "Pat Down";
		sound[] = {"\A3L_Client2\sounds\patdown.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class Cuffed {
		name = "Cuff";
		sound[] = {"\A3L_Client2\sounds\cuff.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class c4_planted {
		name = "C4 planted sound";
		sound[] = {"\A3L_Client2\planted.ogg", 1, 1};
		titles[] = {0, ""};
	};
	
	class turnsignal {
		name = "Turnsignal";
		sound[] = {"\A3L_Client2\turnsignal.ogg", db10, 1, 30};
		titles[] = {0, ""};
	};
	
	class buycarniggah {
		name = "Bought Ride Niggah";
		sound[] = {"\A3L_Client2\buyCar.ogg", 1, 1, 30};
		titles[] = {0, ""};
	};
	
	class salvation {
		name = "salvation";
		sound[] = {"\A3L_Client2\music\mainreaktor-salvation.ogg", 1, 1, 30};
		titles[] = {0, ""};
	};
};
