// Generated by unRap v1.06 by Kegetys

class cfgVehicles {
	class Land;	// External class reference
	
	class Man : Land {
		UnitInfoType = "UnitInfoSoldier";
		hideUnitInfo = "false";
		hideWeaponsCargo = "false";
		hideWeaponsCommander = "true";
		hideWeaponsDriver = "true";
		hideWeaponsGunner = "true";
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_s"};
				speechPlural[] = {"veh_infantry_p"};
			};
		};
		textSingular = "$STR_A3_nameSound_veh_infantry_s";
		textPlural = "$STR_A3_nameSound_veh_infantry_p";
		nameSound = "veh_infantry_s";
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "Man";
		class ViewPilot;	// External class reference
		accuracy = 0.25;	// accuracy needed to recognize type of this target
		camouflage = 2;	// how dificult to spot - bigger - better spotable
		sensitivityEar = 0.5;
		minFireTime = 5;	// minimal time spent firing on single target
		extCameraPosition[] = {0.15, 0, -2};
		class Eventhandlers;	// External class reference
		keepHorizontalPlacement = 1;
	};
};
