// config.bin - 18:39:29 04/18/15, generated in 0.08 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgMusic.hpp"
class RscStandardDisplay;	// External class reference
class RscPicture;	// External class reference
class RscPictureKeepAspect;	// External class reference
#include "RscDisplayStart.hpp"
#include "RscDisplayLoading.hpp"
#include "RscDisplayMain.hpp"
#include "cfgVehicles.hpp"
#include "CfgSounds.hpp"
#include "cfgMods.hpp"
