// Generated by unRap v1.06 by Kegetys

class RscDisplayMain : RscStandardDisplay {
	class controlsBackground {
		class CA_ARMA2 : RscPicture {
			text = "\A3L_Client2\images\logo.paa";
			x = "0.350469 * safezoneW + safezoneX";
			y = "0.247 * safezoneH + safezoneY";
			w = "0.299062 * safezoneW";
			h = "0.462 * safezoneH";
		};
	};
};
