// Generated by unRap v1.06 by Kegetys

class RscDisplayLoading {
	class Variants {
		class LoadingOne {
			idd = -1;
			movingEnable = 0;
			
			class controls {
				class LoadingPic : RscPicture {
					text = "\A3L_Client2\images\logo.paa";
					x = "0.350469 * safezoneW + safezoneX";
					y = "0.247 * safezoneH + safezoneY";
					w = "0.299062 * safezoneW";
					h = "0.462 * safezoneH";
				};
			};
		};
	};
};
