// Generated by unRap v1.06 by Kegetys

class RscDisplayStart : RscStandardDisplay {
	onLoad = "[""onLoad"",_this,""RscDisplayLoading"",'Loading'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf"";";
	onUnload = "[""onUnload"",_this,""RscDisplayLoading"",'Loading'] call compile preprocessfilelinenumbers ""A3\ui_f\scripts\initDisplay.sqf"";";
	
	class controls {
		class Logo : RscPicture {
			idc = 1200;
			text = "\A3L_Client2\images\logo.paa";
			x = "0.350469 * safezoneW + safezoneX";
			y = "0.247 * safezoneH + safezoneY";
			w = "0.299062 * safezoneW";
			h = "0.462 * safezoneH";
		};
	};
};
